#

name: Platform Source Code

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  trigger-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger_Conjur_Retreival
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/<owner>/<repo>/actions/workflows/<workflow_file_name>/dispatches \
            -d '{
              "ref": "main",
              "inputs": {
                "environment": "prod",
                "version": "1.2.3"
              }
            }'
